[[headers]]
for = "*"
Cache-Control = "public, max-age=604800"
[headers.values]
X-Frame-Options = "DENY"
X-Xss-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Feature-Policy = "fullscreen 'self'"
[[headers]]
for = "/index.html"
[headers.values]
Cache-Control = "public, max-age=86400"
[[headers]]
for = "/img/*"
[headers.values]
Cache-Control = "public, max-age=31536000"
